# Generated by Django 5.0.2 on 2024-03-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarios',
            old_name='cobro_año',
            new_name='cobro_ano',
        ),
    ]
