# Generated by Django 5.0.2 on 2024-03-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_rename_cobro_año_salarios_cobro_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puestotrabajo',
            name='salario',
        ),
        migrations.AddField(
            model_name='puestotrabajo',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
